# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack.
matrix:
  include:
  - env: BUILD=cabal
    language: haskell
    ghc: ghc-7.10
  - env: BUILD=cabal
    language: haskell
    ghc: ghc-8.0
  - env: BUILD=cabal
    language: haskell
    ghc: ghc-8.2
  - env: BUILD=stack
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
    compiler: ghc

  allow_failures: []
  # none at the moment

install:
  - export PATH=$HOME/.local/bin::$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    case "$BUILD" in
      stack)
        if [ `uname` = "Darwin" ]
        then
          travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        else
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        fi
      ;;
    cabal)
      ;;
    esac

script:
- |
  set -ex
  if [ "x${RUNTEST}" = "xfalse" ]; then exit 0; fi
  case "$BUILD" in
    stack)
      stack --no-terminal test \
            --install-ghc \
            --bench --no-run-benchmarks
      ;;
    cabal)
      cabal install --only-dependencies --enable-tests
      cabal test
      cabal check
      cabal sdist
      ;;
  esac
  set +ex
