resolver: lts-13.27
system-ghc: true
compiler: ghc-8.9.0

packages: 
- .

extra-deps: 
- github: haskell-foundation/foundation
  commit: 0b6309059f11a90085aa1fe3c2e04c368324b060
  subdirs: 
    - basement

flags: {}

